name: ci-checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: mise
        uses: jdx/mise-action@v2
      - name: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          version-file: 'pyproject.toml'
      - name: poe
        run: uv tool install poethepoet
      - name: dependencies
        run: uvx --from poethepoet poe uv-sync
      - name: check-toml
        run: uv run tb check toml
      - name: check-prettier
        run: uv run tb check prettier
      - name: check-python
        run: uv run tb check python
      - name: check-coverage
        run: uv run tb check coverage
      - name: check-complexity
        run: uv run tb check complexity
      - name: check-basedpyright
        run: uv run tb check basedpyright
